---
title: "New Neutrophil Analyses"
output: github_document
---

### Somalogic Analyses

```{r}
library(knitr)
library(ggplot2)
library(ggrepel)
library(RColorBrewer)
library(plyr)
library(dplyr)
library(DESeq2)
library(openxlsx)
library(corrplot)
library(ggmosaic)
library(cowplot)
library(Seurat)
library(heatmap3)
library(ggpubr)
library(umap)
library(fgsea)
```

```{r}
#prefix <- "~/Downloads/Github/"
#prefix <- "~/Desktop/Github/"
prefix <- "/Volumes/GoogleDrive/.shortcut-targets-by-id/1SQXfCUGIenBLXc4w_p0n7Mufi3JwjFCN/COVID19_Neutrophils/Revision/Final_Steps/Github/"
metadata_long <- read.xlsx(paste0(prefix,"Tables/TableS1.xlsx"), sheet = 4)
qc_data <- read.xlsx(paste0(prefix,"Tables/TableS1.xlsx"), sheet = 9)
genomic_signatures <- read.xlsx(paste0(prefix,"Tables/TableS1.xlsx"), sheet = 10)
metadata_long <- metadata_long[which(metadata_long$Public.ID %in% qc_data$Public.ID),]
metadata_long <- merge(metadata_long, qc_data)
metadata_filtered <- metadata_long[metadata_long$percent.mt < 20 & metadata_long$Genes.Detected > 10000 & metadata_long$Median.Exon.CV < 1 & metadata_long$Exon.CV.MAD < 0.75 & metadata_long$Exonic.Rate*100 > 25 & metadata_long$Median.3..bias < 0.9,]
metadata_filtered <- merge(metadata_filtered, genomic_signatures)
metadata_filtered$Public.Sample.ID <- metadata_filtered$Public.Sample.ID
metadata_filtered$COVID <- mapvalues(metadata_filtered$COVID, from = c(0,1), to = c("Negative","Positive"))

# Color Palette
vermillion <- rgb(213,94,0,max=255)
bluishgreen <- rgb(0,158,115,max=255)
yellow <- rgb(240,228,66,max=255)
blue <- rgb(0,114,178,max=255)
orange <- rgb(230,159,0,max=255)
skyblue <- rgb(86,180,233,max=255)
lightgray <- rgb(211,211,211,max=255)

somalogic <- read.xlsx(paste0(prefix,"Somalogic_Proteomics.xlsx"))
somalogic$Public.Sample.ID <- paste0(somalogic$Public,"_D",somalogic$day)
UniProt_Symbol <- read.xlsx(paste0(prefix,"UniProt_to_GeneID.xlsx"))

somalogic_hugo <- somalogic[,colnames(somalogic) %in% UniProt_Symbol$UniProtID]
somalogic_hugo <- somalogic_hugo[,colnames(somalogic_hugo) %in% UniProt_Symbol$UniProtID]
somalogic_hugo <- somalogic_hugo[,!(colnames(somalogic_hugo) %in% c("Q9HDB5","P58400"))]
UniProt_Symbol_somalogic <- UniProt_Symbol[UniProt_Symbol$UniProtID %in% colnames(somalogic_hugo),]
UniProt_Symbol_somalogic <- UniProt_Symbol_somalogic[!(is.na(UniProt_Symbol_somalogic$Gene)),]
somalogic_hugo <- somalogic_hugo[,colnames(somalogic_hugo) %in% UniProt_Symbol_somalogic$UniProtID]
rownames(UniProt_Symbol_somalogic) <- UniProt_Symbol_somalogic$UniProtID
colnames(somalogic_hugo) <- UniProt_Symbol_somalogic[colnames(somalogic_hugo),]$Gene
somalogic_hugo <- cbind(somalogic$Public,somalogic$day,somalogic$sample_barcode,somalogic$Public.Sample.ID,somalogic_hugo)
colnames(somalogic_hugo)[1:4] <- c("Public","day","sample_barcode","Public.Sample.ID")

somalogic <- somalogic[somalogic$Public.Sample.ID %in% metadata_filtered$Public.Sample.ID,]
somalogic_hugo <- somalogic_hugo[somalogic_hugo$Public.Sample.ID %in% metadata_filtered$Public.Sample.ID,]
metadata_filtered <- metadata_filtered[metadata_filtered$Public.Sample.ID %in% somalogic$Public.Sample.ID,]

somalogic <- merge(somalogic, metadata_filtered, by = "Public.Sample.ID")
somalogic$cluster_neuhi <- factor(somalogic$cluster_neuhi)
somalogic_hugo <- merge(somalogic_hugo, metadata_filtered, by = "Public.Sample.ID")
somalogic_hugo$cluster_neuhi <- factor(somalogic_hugo$cluster_neuhi)

gmt.file <- gmtPathways(paste0(prefix,"all_gene_sets.gmt"))
```

ELANE, CTSG, LCN2/NGAL, AZU1, PRTN3

```{r}
poi <- "PRTN3"
id <- UniProt_Symbol$UniProtID[which(UniProt_Symbol$Gene == poi)]

my.cols <- brewer.pal(3, "RdBu")
id <- UniProt_Symbol$UniProtID[which(UniProt_Symbol$Gene == poi)]

dat <- as.data.frame(somalogic[somalogic$COVID == "Positive" & somalogic$day %in% c("0","3","7"),colnames(somalogic) %in% c("day","severity.max", "cluster_neuhi",id)])
dat$zscore <- (dat[,2]-mean(dat[,2]))/sd(dat[,2])

ggplot(dat, aes_string(x = "day", y = "zscore", fill = "severity.max")) + theme_bw() + geom_boxplot(outlier.shape = NA) + xlab("") + theme(panel.grid = element_blank(), legend.position = "none") + geom_point(aes(colour = severity.max), position = position_jitterdodge(jitter.height = 0, jitter.width = 0.2), fill = "black", alpha = 0.2, size = 0.5) + ggtitle(paste0(poi,"/",id)) + stat_compare_means() + scale_fill_manual(values = c(my.cols[3],my.cols[1])) + scale_colour_manual(values = c("black","black")) + coord_fixed(ratio = .5)
```

```{r}
id <- UniProt_Symbol$UniProtID[which(UniProt_Symbol$Gene == poi)]
ggplot(as.data.frame(somalogic[somalogic$COVID == "Positive" & somalogic$day %in% c("0","3","7") & somalogic$severity.max == "severe",colnames(somalogic) %in% c("day","severity.max", "Acuity.max", "cluster_neuhi",id)]), aes_string(x = "day", y = id, fill = "Acuity.max")) + theme_bw() + geom_boxplot(outlier.shape = NA) + xlab("") + theme(panel.grid = element_blank()) + geom_point(aes(colour = Acuity.max), position = position_jitterdodge(jitter.height = 0, jitter.width = 0.2), fill = "black", pch = 19, alpha = 0.2) + ggtitle(paste0(poi,"/",id)) + stat_compare_means() + scale_fill_manual(values = c("red","navy")) + scale_colour_manual(values = c("black","black"))

ggplot(as.data.frame(somalogic[somalogic$COVID == "Positive",colnames(somalogic) %in% c("cluster_neuhi",id)]), aes_string(x = "cluster_neuhi", y = id, fill = "cluster_neuhi")) + theme_bw() + geom_boxplot(outlier.shape = NA) + xlab("") + theme(legend.position = "none", panel.grid = element_blank()) + geom_jitter(fill = "black", pch = 21, width = 0.2, alpha = 0.2) + ggtitle(paste0(poi,"/",id)) + stat_compare_means() + scale_fill_manual(values = c(orange, skyblue, bluishgreen, yellow, blue, vermillion, "#bd6bd9"))
id <- UniProt_Symbol$UniProtID[which(UniProt_Symbol$Gene == poi)]
ggplot(as.data.frame(somalogic[somalogic$day == "0" & somalogic$COVID == "Positive",colnames(somalogic) %in% c("cluster_neuhi",id)]), aes_string(x = "cluster_neuhi", y = id, fill = "cluster_neuhi")) + theme_bw() + geom_boxplot(outlier.shape = NA) + xlab("") + theme(legend.position = "none", panel.grid = element_blank()) + geom_jitter(fill = "black", pch = 21, width = 0.2, alpha = 0.2) + ggtitle(paste0("D0 ",poi,"/",id)) + stat_compare_means() + scale_fill_manual(values = c(orange, skyblue, bluishgreen, yellow, blue, vermillion, "#bd6bd9"))
ggplot(as.data.frame(somalogic[somalogic$day == "3" & somalogic$COVID == "Positive",colnames(somalogic) %in% c("cluster_neuhi",id)]), aes_string(x = "cluster_neuhi", y = id, fill = "cluster_neuhi")) + theme_bw() + geom_boxplot(outlier.shape = NA) + xlab("") + theme(legend.position = "none", panel.grid = element_blank()) + geom_jitter(fill = "black", pch = 21, width = 0.2, alpha = 0.2) + ggtitle(paste0("D3 ",poi,"/",id)) + stat_compare_means() + scale_fill_manual(values = c(orange, skyblue, bluishgreen, yellow, blue, vermillion, "#bd6bd9"))
ggplot(as.data.frame(somalogic[somalogic$day == "7" & somalogic$COVID == "Positive",colnames(somalogic) %in% c("cluster_neuhi",id)]), aes_string(x = "cluster_neuhi", y = id, fill = "cluster_neuhi")) + theme_bw() + geom_boxplot(outlier.shape = NA) + xlab("") + theme(legend.position = "none", panel.grid = element_blank()) + geom_jitter(fill = "black", pch = 21, width = 0.2, alpha = 0.2) + ggtitle(paste0("D7 ",poi,"/",id)) + stat_compare_means() + scale_fill_manual(values = c(orange, skyblue, bluishgreen, yellow, blue, vermillion, "#bd6bd9"))

somalogic$REACTOME_NEUTROPHIL_DEGRANULATION <- as.numeric(somalogic$REACTOME_NEUTROPHIL_DEGRANULATION)
id <- UniProt_Symbol$UniProtID[which(UniProt_Symbol$Gene == poi)]
ggplot(as.data.frame(somalogic[,colnames(somalogic) %in% c("cluster_neuhi",id,"REACTOME_NEUTROPHIL_DEGRANULATION")]), aes_string(x = "REACTOME_NEUTROPHIL_DEGRANULATION", y = id)) + theme_bw() + geom_point() + theme(legend.position = "none", panel.grid = element_blank()) + ggtitle(paste0(poi,"/",id)) + geom_smooth(method = "lm")

somalogic_hugo$PROTEIN_REACTOME_NEUTROPHIL_DEGRANULATION <- rowMeans(apply(somalogic_hugo[,colnames(somalogic_hugo) %in% gmt.file$REACTOME_NEUTROPHIL_DEGRANULATION],2,scale))
somalogic_hugo$REACTOME_NEUTROPHIL_DEGRANULATION <- as.numeric(somalogic_hugo$REACTOME_NEUTROPHIL_DEGRANULATION)
tmp_ct <- cor.test(somalogic_hugo$REACTOME_NEUTROPHIL_DEGRANULATION,somalogic_hugo$PROTEIN_REACTOME_NEUTROPHIL_DEGRANULATION,method="spearman")
tmp_ct_label <- paste0("rho=",round(tmp_ct$estimate,digits=2)," p=",signif(tmp_ct$p.value,digits=2))
ggplot(as.data.frame(somalogic_hugo), aes(x=REACTOME_NEUTROPHIL_DEGRANULATION,y=PROTEIN_REACTOME_NEUTROPHIL_DEGRANULATION)) + theme_bw() + geom_point() + theme(legend.position = "none", panel.grid = element_blank()) + geom_smooth(method = "lm") + annotate(geom="text",x=2.4,y=0.75,label=tmp_ct_label)

ggplot(as.data.frame(somalogic_hugo[somalogic_hugo$COVID == "Positive" & somalogic_hugo$day %in% c("0","3","7") & somalogic_hugo$severity.max == "severe",]), aes(x = day, y = PROTEIN_REACTOME_NEUTROPHIL_DEGRANULATION, fill = Acuity.max)) + theme_bw() + geom_boxplot(outlier.shape = NA) + xlab("") + theme(panel.grid = element_blank()) + geom_point(aes(colour = Acuity.max), position = position_jitterdodge(jitter.height = 0, jitter.width = 0.2), fill = "black", pch = 19, alpha = 0.2) + stat_compare_means(size=3.5) + scale_fill_manual(values = c("red","navy")) + scale_colour_manual(values = c("black","black"))

ggplot(as.data.frame(somalogic_hugo[somalogic_hugo$COVID == "Positive",]), aes(x=cluster_neuhi,y = PROTEIN_REACTOME_NEUTROPHIL_DEGRANULATION, fill = cluster_neuhi)) + theme_bw() + geom_boxplot(outlier.shape = NA) + xlab("") + theme(legend.position = "none", panel.grid = element_blank()) + geom_jitter(fill = "black", pch = 21, width = 0.2, alpha = 0.2) + stat_compare_means() + scale_fill_manual(values = c(orange, skyblue, bluishgreen, yellow, blue, vermillion, "#bd6bd9"))
ggplot(as.data.frame(somalogic_hugo[somalogic_hugo$day == "0" & somalogic_hugo$COVID == "Positive",]), aes(x = cluster_neuhi, y = PROTEIN_REACTOME_NEUTROPHIL_DEGRANULATION, fill = cluster_neuhi)) + theme_bw() + geom_boxplot(outlier.shape = NA) + xlab("") + theme(legend.position = "none", panel.grid = element_blank()) + geom_jitter(fill = "black", pch = 21, width = 0.2, alpha = 0.2) + ggtitle("D0") + stat_compare_means() + scale_fill_manual(values = c(orange, skyblue, bluishgreen, yellow, blue, vermillion, "#bd6bd9"))
ggplot(as.data.frame(somalogic_hugo[somalogic_hugo$day == "3" & somalogic_hugo$COVID == "Positive",]), aes(x = cluster_neuhi, y = PROTEIN_REACTOME_NEUTROPHIL_DEGRANULATION, fill = cluster_neuhi)) + theme_bw() + geom_boxplot(outlier.shape = NA) + xlab("") + theme(legend.position = "none", panel.grid = element_blank()) + geom_jitter(fill = "black", pch = 21, width = 0.2, alpha = 0.2) + ggtitle("D3") + stat_compare_means() + scale_fill_manual(values = c(orange, skyblue, bluishgreen, yellow, blue, vermillion, "#bd6bd9"))
ggplot(as.data.frame(somalogic_hugo[somalogic_hugo$day == "7" & somalogic_hugo$COVID == "Positive",]), aes(x = cluster_neuhi, y = PROTEIN_REACTOME_NEUTROPHIL_DEGRANULATION, fill = cluster_neuhi)) + theme_bw() + geom_boxplot(outlier.shape = NA) + xlab("") + theme(legend.position = "none", panel.grid = element_blank()) + geom_jitter(fill = "black", pch = 21, width = 0.2, alpha = 0.2) + ggtitle("D7") + stat_compare_means() + scale_fill_manual(values = c(orange, skyblue, bluishgreen, yellow, blue, vermillion, "#bd6bd9"))

somalogic_hugo$PROTEIN_GO_AZUROPHIL_GRANULE <- rowMeans(apply(somalogic_hugo[,colnames(somalogic_hugo) %in% gmt.file$GO_AZUROPHIL_GRANULE],2,scale))
ggplot(as.data.frame(somalogic_hugo), aes(x=as.numeric(GO_AZUROPHIL_GRANULE),y=PROTEIN_GO_AZUROPHIL_GRANULE)) + theme_bw() + geom_point() + theme(legend.position = "none", panel.grid = element_blank()) + geom_smooth(method = "lm")

somalogic_hugo$PROTEIN_GO_SPECIFIC_GRANULE <- rowMeans(apply(somalogic_hugo[,colnames(somalogic_hugo) %in% gmt.file$GO_SPECIFIC_GRANULE],2,scale))
ggplot(as.data.frame(somalogic_hugo), aes(x=as.numeric(GO_SPECIFIC_GRANULE),y=PROTEIN_GO_SPECIFIC_GRANULE)) + theme_bw() + geom_point() + theme(legend.position = "none", panel.grid = element_blank()) + geom_smooth(method = "lm")

somalogic_hugo$PROTEIN_GO_TERTIARY_GRANULE <- rowMeans(apply(somalogic_hugo[,colnames(somalogic_hugo) %in% gmt.file$GO_TERTIARY_GRANULE],2,scale))
ggplot(as.data.frame(somalogic_hugo), aes(x=as.numeric(GO_TERTIARY_GRANULE),y=PROTEIN_GO_TERTIARY_GRANULE)) + theme_bw() + geom_point() + theme(legend.position = "none", panel.grid = element_blank()) + geom_smooth(method = "lm")


ggplot(as.data.frame(somalogic_hugo), aes(x=as.numeric(REACTOME_NEUTROPHIL_DEGRANULATION),y=scale(CTSG))) + theme_bw() + geom_point() + theme(legend.position = "none", panel.grid = element_blank()) + geom_smooth(method = "lm")
ggplot(as.data.frame(somalogic_hugo), aes(x=as.numeric(GO_AZUROPHIL_GRANULE),y=scale(CTSG))) + theme_bw() + geom_point() + theme(legend.position = "none", panel.grid = element_blank()) + geom_smooth(method = "lm")


ggplot(as.data.frame(somalogic_hugo), aes(x=as.numeric(REACTOME_NEUTROPHIL_DEGRANULATION),y=scale(ELANE))) + theme_bw() + geom_point() + theme(legend.position = "none", panel.grid = element_blank()) + geom_smooth(method = "lm")
ggplot(as.data.frame(somalogic_hugo), aes(x=as.numeric(GO_AZUROPHIL_GRANULE),y=scale(ELANE))) + theme_bw() + geom_point() + theme(legend.position = "none", panel.grid = element_blank()) + geom_smooth(method = "lm")


ggplot(as.data.frame(somalogic_hugo), aes(x=as.numeric(REACTOME_NEUTROPHIL_DEGRANULATION),y=scale(LCN2))) + theme_bw() + geom_point() + theme(legend.position = "none", panel.grid = element_blank()) + geom_smooth(method = "lm")
ggplot(as.data.frame(somalogic_hugo), aes(x=as.numeric(GO_TERTIARY_GRANULE),y=scale(LCN2))) + theme_bw() + geom_point() + theme(legend.position = "none", panel.grid = element_blank()) + geom_smooth(method = "lm")


ggplot(as.data.frame(somalogic_hugo), aes(x=as.numeric(REACTOME_NEUTROPHIL_DEGRANULATION),y=scale(PRTN3))) + theme_bw() + geom_point() + theme(legend.position = "none", panel.grid = element_blank()) + geom_smooth(method = "lm")
ggplot(as.data.frame(somalogic_hugo), aes(x=as.numeric(GO_AZUROPHIL_GRANULE),y=scale(PRTN3))) + theme_bw() + geom_point() + theme(legend.position = "none", panel.grid = element_blank()) + geom_smooth(method = "lm")

ggplot(as.data.frame(somalogic_hugo), aes(x=as.numeric(REACTOME_NEUTROPHIL_DEGRANULATION),y=scale(LTF))) + theme_bw() + geom_point() + theme(legend.position = "none", panel.grid = element_blank()) + geom_smooth(method = "lm")
ggplot(as.data.frame(somalogic_hugo), aes(x=as.numeric(GO_SPECIFIC_GRANULE),y=scale(LTF))) + theme_bw() + geom_point() + theme(legend.position = "none", panel.grid = element_blank()) + geom_smooth(method = "lm")


```

```{r}
metadata_temp <- read.xlsx(paste0(prefix,"Tables/TableS1.xlsx"), sheet = 2)
metadata_temp$nmf.0 <- NA
metadata_temp$nmf.3 <- NA
metadata_temp$nmf.7 <- NA
metadata_temp$nmf.E <- NA

for (i in 1:nrow(metadata_temp)){
  patient <- metadata_temp$Public.ID[i]
  temp <- metadata_filtered[metadata_filtered$Public.ID == patient,]
  if (nrow(temp) >= 1){
    temp0 <- temp[temp$Day == "D0",]
    if (nrow(temp0) == 1){
      metadata_temp$nmf.0[i] <- temp0$cluster_neuhi[1]
    }
    temp3 <- temp[temp$Day == "D3",]
    if (nrow(temp3) == 1){
      metadata_temp$nmf.3[i] <- temp3$cluster_neuhi[1]
    }
    temp7 <- temp[temp$Day == "D7",]
    if (nrow(temp7) == 1){
      metadata_temp$nmf.7[i] <- temp7$cluster_neuhi[1]
    }
    tempE <- temp[temp$Day == "DE",]
    if (nrow(tempE) == 1){
      metadata_temp$nmf.E[i] <- tempE$cluster_neuhi[1]
    }
  }
}

metadata_completecases <- metadata_temp[complete.cases(metadata_temp$nmf.0),]
metadata_completecases <- metadata_completecases[complete.cases(metadata_completecases$nmf.3),]
metadata_completecases <- metadata_completecases[complete.cases(metadata_completecases$nmf.7),]
```

### CitH3 ELISA

```{r}
library(dr4pl)
elisa_long <- read.xlsx(paste0(prefix,"CitH3_ELISA.xlsx"), sheet = 1)
#elisa_long <- read.xlsx("~/Desktop/Follow_Up_Experiments.xlsx",sheet = 2)

standards_p1 <- elisa_long[elisa_long$severity.max == "Standard" & elisa_long$plate == "P1",]
elisa_p1 <- elisa_long[elisa_long$severity.max != "Standard" & elisa_long$plate == "P1",]

a <- dr4pl(dose = as.numeric(standards_p1[standards_p1$Day != "",]$absorbance450),
            response = standards_p1[standards_p1$Day != "",]$concentration,
            method.init = "logistic")
plot(a)

conversion <- function(ab) {
  th1 <- a$parameters[1]
  th2 <- a$parameters[2]
  th3 <- a$parameters[3]
  th4 <- a$parameters[4]
  conc <- th1+(th4-th1)/(1+(ab/th2)^th3)
  return(conc)
}

for (i in 1:nrow(elisa_p1)){
  elisa_p1$CitH3[i] <- conversion(elisa_p1$absorbance450[i])
}
elisa_p1$CitH3 <- elisa_p1$CitH3 * 9 #Samples were diluted 1:2 for the ELISA

for (i in 1:nrow(standards_p1)){
  standards_p1$CitH3[i] <- conversion(standards_p1$absorbance450[i])
}

elisa_p1 <- rbind(elisa_p1,standards_p1)
elisa_p1$CitH3 <- elisa_p1$CitH3 - mean(elisa_p1$CitH3[elisa_p1$Day == "S8"])

standards_p2 <- elisa_long[elisa_long$severity.max == "Standard" & elisa_long$plate == "P2",]
elisa_p2 <- elisa_long[elisa_long$severity.max != "Standard" & elisa_long$plate == "P2",]

a <- dr4pl(dose = as.numeric(standards_p2[standards_p2$Day != "",]$absorbance450),
            response = standards_p2[standards_p2$Day != "",]$concentration,
            method.init = "logistic")
plot(a)

conversion <- function(ab) {
  th1 <- a$parameters[1]
  th2 <- a$parameters[2]
  th3 <- a$parameters[3]
  th4 <- a$parameters[4]
  conc <- th1+(th4-th1)/(1+(ab/th2)^th3)
  return(conc)
}

for (i in 1:nrow(elisa_p2)){
  elisa_p2$CitH3[i] <- conversion(elisa_p2$absorbance450[i])
}
elisa_p2$CitH3 <- elisa_p2$CitH3 * 9 #Samples were diluted 1:2 for the ELISA

for (i in 1:nrow(standards_p2)){
  standards_p2$CitH3[i] <- conversion(standards_p2$absorbance450[i])
}

elisa_p2 <- rbind(elisa_p2,standards_p2)
elisa_p2$CitH3 <- elisa_p2$CitH3 - mean(elisa_p2$CitH3[elisa_p2$Day == "S8"])

standards_p3 <- elisa_long[elisa_long$severity.max == "Standard" & elisa_long$plate == "P3",]
elisa_p3 <- elisa_long[elisa_long$severity.max != "Standard" & elisa_long$plate == "P3",]

a <- dr4pl(dose = as.numeric(standards_p3[standards_p3$Day != "",]$absorbance450),
            response = standards_p3[standards_p3$Day != "",]$concentration,
            method.init = "logistic")
plot(a)

conversion <- function(ab) {
  th1 <- a$parameters[1]
  th2 <- a$parameters[2]
  th3 <- a$parameters[3]
  th4 <- a$parameters[4]
  conc <- th1+(th4-th1)/(1+(ab/th2)^th3)
  return(conc)
}

for (i in 1:nrow(elisa_p3)){
  elisa_p3$CitH3[i] <- conversion(elisa_p3$absorbance450[i])
}
elisa_p3$CitH3 <- elisa_p3$CitH3 * 9 #Samples were diluted 1:2 for the ELISA

for (i in 1:nrow(standards_p3)){
  standards_p3$CitH3[i] <- conversion(standards_p3$absorbance450[i])
}

elisa_p3 <- rbind(elisa_p3,standards_p3)
elisa_p3$CitH3 <- elisa_p3$CitH3 - mean(elisa_p3$CitH3[elisa_p3$Day == "S8"])

elisa_res <- rbind(elisa_p1,elisa_p2,elisa_p3)
```

```{r}
my.cols <- brewer.pal(3,"RdBu")
ggplot(elisa_res[elisa_res$Day %in% c("H","D0","D3","D7"),], aes(x = factor(plate), y = as.numeric(CitH3), fill = factor(plate))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge()) + theme_bw() + stat_compare_means() + ylab("CitH3 Concentration") + xlab("Plate") + scale_y_log10()
```

```{r}
my.cols <- brewer.pal(3,"RdBu")
ggplot(elisa_res[elisa_res$severity.max == "Standard",], aes(x = factor(plate), y = as.numeric(CitH3), fill = factor(plate))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge()) + theme_bw() + stat_compare_means() + ylab("CitH3 Concentration") + xlab("Plate") + scale_y_log10()
```

```{r}
my.cols <- brewer.pal(3,"RdBu")
ggplot(elisa_res[elisa_res$severity.max == "Standard",], aes(x = factor(plate), y = as.numeric(CitH3))) + geom_boxplot(outlier.shape = NA, fill = "grey") + geom_point(aes(colour = Day), position = position_jitterdodge()) + theme_bw() + stat_compare_means() + ylab("CitH3 Concentration") + xlab("Plate")
```

```{r}
my.cols <- brewer.pal(3,"RdBu")
ggplot(elisa_res[elisa_res$severity.max == "Standard",], aes(x = factor(plate), y = as.numeric(CitH3))) + geom_boxplot(outlier.shape = NA, fill = "grey") + geom_point(aes(colour = Day), position = position_jitterdodge()) + theme_bw() + stat_compare_means() + ylab("CitH3 Concentration") + xlab("Plate") + scale_y_log10()
```

```{r}
my.cols <- brewer.pal(3,"RdBu")
ggplot(elisa_res[elisa_res$severity.max == "Standard",], aes(x = factor(plate), y = as.numeric(absorbance450))) + geom_boxplot(outlier.shape = NA, fill = "grey") + geom_point(aes(colour = Day), position = position_jitterdodge()) + theme_bw() + stat_compare_means() + ylab("Absorbance 450") + xlab("Plate")
```

```{r}
my.cols <- brewer.pal(3,"RdBu")
ggplot(elisa_res[elisa_res$severity.max == "Standard",], aes(x = factor(plate), y = as.numeric(absorbance450))) + geom_boxplot(outlier.shape = NA, fill = "grey") + geom_point(aes(colour = Day), position = position_jitterdodge()) + theme_bw() + stat_compare_means() + ylab("Absorbance 450") + xlab("Plate") + scale_y_log10()
```

```{r}
my.cols <- brewer.pal(3,"RdBu")
ggplot(elisa_res[elisa_res$Day %in% c("D0","D3","D7"),], aes(x = factor(Day), y = as.numeric(CitH3), fill = factor(severity.max))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge(), size = 0.5, alpha = 0.2) + theme_bw() + stat_compare_means() + ylab("CitH3 Concentration") + xlab("Day") + scale_fill_manual(values = c("green",my.cols[3],my.cols[1])) + scale_y_log10() + theme(legend.position = "none")
```

```{r}
my.cols <- brewer.pal(3,"RdBu")
ggplot(elisa_res[elisa_res$Day %in% c("D0","D3","D7","H") & elisa_res$plate == "P1",], aes(x = factor(Day), y = as.numeric(CitH3), fill = factor(severity.max))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge()) + theme_bw() + stat_compare_means() + ylab("CitH3 Concentration") + xlab("Day") + scale_fill_manual(values = c(my.cols[3],my.cols[1],"green"))
ggplot(elisa_res[elisa_res$Day %in% c("D0","D3","D7","H") & elisa_res$plate == "P2",], aes(x = factor(Day), y = as.numeric(CitH3), fill = factor(severity.max))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge()) + theme_bw() + stat_compare_means() + ylab("CitH3 Concentration") + xlab("Day") + scale_fill_manual(values = c(my.cols[3],my.cols[1],"green"))
ggplot(elisa_res[elisa_res$Day %in% c("D0","D3","D7","H") & elisa_res$plate == "P3",], aes(x = factor(Day), y = as.numeric(CitH3), fill = factor(severity.max))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge()) + theme_bw() + stat_compare_means() + ylab("CitH3 Concentration") + xlab("Day") + scale_fill_manual(values = c(my.cols[3],my.cols[1],"green"))
```

```{r}
my.cols <- brewer.pal(3,"RdBu")
p <- ggplot(elisa_res[elisa_res$Day %in% c("D0","D3","D7"),], aes(x = factor(Day), y = as.numeric(CitH3), fill = factor(Acuity.max, levels = c("4","3","2","1")))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge(), size = 0.5) + theme_bw() + stat_compare_means() + ylab("CitH3 Concentration") + xlab("Day") + scale_fill_manual(values = rev(c("red",my.cols[1],blue,"purple"))) + scale_y_log10()
p$labels$fill <- "Acuity.max"
p
```

```{r}
my.cols <- brewer.pal(3,"RdBu")
ggplot(elisa_res[elisa_res$Day %in% c("D0","D3","D7"),], aes(x = factor(cluster_neuhi), y = as.numeric(CitH3), fill = factor(cluster_neuhi))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge(jitter.width = 1.5), size = 0.5, alpha = 0.2) + theme_bw() + stat_compare_means() + ylab("CitH3 Concentration") + xlab("NMF") + scale_fill_manual(values = c(orange,skyblue,bluishgreen,yellow,blue,vermillion,"purple")) + scale_y_log10()
ggplot(elisa_res[elisa_res$Day %in% c("D0"),], aes(x = factor(cluster_neuhi), y = as.numeric(CitH3), fill = factor(cluster_neuhi))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge()) + theme_bw() + stat_compare_means() + ylab("CitH3 Concentration") + xlab("Day") + scale_fill_manual(values = c(orange,skyblue,bluishgreen,yellow,blue,vermillion,"purple"))
ggplot(elisa_res[elisa_res$Day %in% c("D3"),], aes(x = factor(cluster_neuhi), y = as.numeric(CitH3), fill = factor(cluster_neuhi))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge()) + theme_bw() + stat_compare_means() + ylab("CitH3 Concentration") + xlab("Day") + scale_fill_manual(values = c(orange,skyblue,bluishgreen,yellow,blue,vermillion,"purple"))
ggplot(elisa_res[elisa_res$Day %in% c("D7"),], aes(x = factor(cluster_neuhi), y = as.numeric(CitH3), fill = factor(cluster_neuhi))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge()) + theme_bw() + stat_compare_means() + ylab("CitH3 Concentration") + xlab("Day") + scale_fill_manual(values = c(orange,skyblue,bluishgreen,yellow,blue,vermillion,"purple"))
```

```{r}
elisa_res_cov <- elisa_res[elisa_res$Public.Sample.ID %in% somalogic$Public.Sample.ID,]
elisa_res_cov_netosis <- merge(elisa_res_cov,somalogic[,c("Public.Sample.ID","NETosis","NETosis_Mukhopadhyay")],all.x=TRUE,by="Public.Sample.ID")
elisa_res_cov_netosis$NETosis <- as.numeric(elisa_res_cov_netosis$NETosis)
tmp_ct2 <- cor.test(elisa_res_cov_netosis$NETosis[as.numeric(elisa_res_cov_netosis$CitH3)>0],log10(as.numeric(elisa_res_cov_netosis$CitH3)[as.numeric(elisa_res_cov_netosis$CitH3)>0]),method="spearman")
tmp_ct2_lab <- paste0("rho=",round(tmp_ct2$estimate,2)," p=",signif(tmp_ct2$p.value,3))
ggplot(elisa_res_cov_netosis[elisa_res_cov_netosis$Day %in% c("D0","D3","D7"),], aes(x = as.numeric(NETosis), y = as.numeric(CitH3))) + geom_point() + geom_smooth(method="lm") + theme_bw() + ylab("CitH3 Concentration") + xlab("RNA-Seq NETosis metagene") + scale_y_log10() + annotate(geom="text",x=-0.5,y=100,label=tmp_ct2_lab)
```

FCGR1A, FCGR1B, FCGR2A, FCGR2B, FCGR3A, FCGR3B, FCAR, FCGRT

```{r}
metadata_long <- read.xlsx(paste0(prefix,"Tables/TableS1.xlsx"), sheet = 4)
qc_data <- read.xlsx(paste0(prefix,"Tables/TableS1.xlsx"), sheet = 9)
genomic_signatures <- read.xlsx(paste0(prefix,"Tables/TableS1.xlsx"), sheet = 10)
metadata_long <- metadata_long[which(metadata_long$Public.ID %in% qc_data$Public.ID),]
metadata_long <- merge(metadata_long, qc_data)
metadata_filtered <- metadata_long[metadata_long$percent.mt < 20 & metadata_long$Genes.Detected > 10000 & metadata_long$Median.Exon.CV < 1 & metadata_long$Exon.CV.MAD < 0.75 & metadata_long$Exonic.Rate*100 > 25 & metadata_long$Median.3..bias < 0.9,]
metadata_filtered <- merge(metadata_filtered, genomic_signatures)
metadata_filtered$Public.Sample.ID <- metadata_filtered$Public.Sample.ID
metadata_filtered$COVID <- mapvalues(metadata_filtered$COVID, from = c(0,1), to = c("Negative","Positive"))

genepc <- read.delim(paste0(prefix,"Ensembl_to_Symbol.txt"))
TPM <- read.xlsx(paste0(prefix,"Tables/TableS1.xlsx"), sheet = 8, rowNames = TRUE)
logTPM <- log2(TPM + 1)
logTPM_filtered <- logTPM[,colnames(logTPM) %in% rownames(metadata_filtered)]

Count <- read.table(gzfile(paste0(prefix,"Tables/Count_S1F.txt.gz")),sep="\t")
colnames(Count) <- Count[1,]
Count <- Count[-1,]
Count <- Count[,-2]
rownames(Count) <- Count[,1]
nams <- Count[,1]
Count <- Count[,-1]
Count <- as.data.frame(apply(Count,2,as.numeric))
rownames(Count) <- nams
TPM <- read.table(gzfile(paste0(prefix,"Tables/TPM_S1G.txt.gz")),sep="\t")
colnames(TPM) <- TPM[1,]
TPM <- TPM[-1,]
TPM <- TPM[,-2]
rownames(TPM) <- TPM[,1]
nams <- TPM[,1]
TPM <- TPM[,-1]
TPM <- as.data.frame(apply(TPM,2,as.numeric))
rownames(TPM) <- nams
logTPM <- log2(TPM + 1)
logTPM_filtered <- logTPM[,colnames(logTPM) %in% metadata_filtered$Public.Sample.ID]


gene <- "FCGR1A"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
my.cols <- brewer.pal(3, "RdBu")
p1 <- ggplot(metadata_temp, aes(x = factor(Day), y = as.numeric(GOI), fill = factor(severity.max))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge(), alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + xlab("Day") + scale_fill_manual(values = my.cols[c(3,1)]) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

gene <- "FCGR1B"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
my.cols <- brewer.pal(3, "RdBu")
p2 <- ggplot(metadata_temp, aes(x = factor(Day), y = as.numeric(GOI), fill = factor(severity.max))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge(), alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + xlab("Day") + scale_fill_manual(values = my.cols[c(3,1)]) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

gene <- "FCGR2A"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
my.cols <- brewer.pal(3, "RdBu")
p3 <- ggplot(metadata_temp, aes(x = factor(Day), y = as.numeric(GOI), fill = factor(severity.max))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge(), alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + xlab("Day") + scale_fill_manual(values = my.cols[c(3,1)]) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

gene <- "FCGR2B"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
my.cols <- brewer.pal(3, "RdBu")
p4 <- ggplot(metadata_temp, aes(x = factor(Day), y = as.numeric(GOI), fill = factor(severity.max))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge(), alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + xlab("Day") + scale_fill_manual(values = my.cols[c(3,1)]) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

gene <- "FCGR3A"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
my.cols <- brewer.pal(3, "RdBu")
p5 <- ggplot(metadata_temp, aes(x = factor(Day), y = as.numeric(GOI), fill = factor(severity.max))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge(), alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + xlab("Day") + scale_fill_manual(values = my.cols[c(3,1)]) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

gene <- "FCGR3B"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
my.cols <- brewer.pal(3, "RdBu")
p6 <- ggplot(metadata_temp, aes(x = factor(Day), y = as.numeric(GOI), fill = factor(severity.max))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge(), alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + xlab("Day") + scale_fill_manual(values = my.cols[c(3,1)]) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

gene <- "FCAR"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
my.cols <- brewer.pal(3, "RdBu")
p7 <- ggplot(metadata_temp, aes(x = factor(Day), y = as.numeric(GOI), fill = factor(severity.max))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge(), alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + xlab("Day") + scale_fill_manual(values = my.cols[c(3,1)]) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

gene <- "FCGRT"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
my.cols <- brewer.pal(3, "RdBu")
p8 <- ggplot(metadata_temp, aes(x = factor(Day), y = as.numeric(GOI), fill = factor(severity.max))) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge(), alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + xlab("Day") + scale_fill_manual(values = my.cols[c(3,1)]) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

cowplot::plot_grid(p1,p2,p3,p4,p5,p6,p7,p8,ncol=4)
```

```{r}
gene <- "FCGR1A"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_filtered$cluster_neuhi <- mapvalues(metadata_filtered$cluster_neuhi, from = c("1","2","3","4","5","6","7"), to = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_filtered$cluster_neuhi <- factor(metadata_filtered$cluster_neuhi, levels = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
kruskal.test(g = metadata_temp$cluster_neuhi, x = metadata_temp$GOI)$p.value
p1 <- ggplot(metadata_temp, aes(x = factor(cluster_neuhi), y = as.numeric(GOI), fill = cluster_neuhi)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = 0.3, alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + scale_fill_manual(values = c(orange,skyblue,bluishgreen,yellow,blue,vermillion,"purple")) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

gene <- "FCGR1B"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_filtered$cluster_neuhi <- mapvalues(metadata_filtered$cluster_neuhi, from = c("1","2","3","4","5","6","7"), to = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_filtered$cluster_neuhi <- factor(metadata_filtered$cluster_neuhi, levels = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
kruskal.test(g = metadata_temp$cluster_neuhi, x = metadata_temp$GOI)$p.value
p2 <- ggplot(metadata_temp, aes(x = factor(cluster_neuhi), y = as.numeric(GOI), fill = cluster_neuhi)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = 0.3, alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + scale_fill_manual(values = c(orange,skyblue,bluishgreen,yellow,blue,vermillion,"purple")) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

gene <- "FCGR2A"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_filtered$cluster_neuhi <- mapvalues(metadata_filtered$cluster_neuhi, from = c("1","2","3","4","5","6","7"), to = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_filtered$cluster_neuhi <- factor(metadata_filtered$cluster_neuhi, levels = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
kruskal.test(g = metadata_temp$cluster_neuhi, x = metadata_temp$GOI)$p.value
p3 <- ggplot(metadata_temp, aes(x = factor(cluster_neuhi), y = as.numeric(GOI), fill = cluster_neuhi)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = 0.3, alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + scale_fill_manual(values = c(orange,skyblue,bluishgreen,yellow,blue,vermillion,"purple")) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

gene <- "FCGR2B"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_filtered$cluster_neuhi <- mapvalues(metadata_filtered$cluster_neuhi, from = c("1","2","3","4","5","6","7"), to = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_filtered$cluster_neuhi <- factor(metadata_filtered$cluster_neuhi, levels = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
kruskal.test(g = metadata_temp$cluster_neuhi, x = metadata_temp$GOI)$p.value
p4 <- ggplot(metadata_temp, aes(x = factor(cluster_neuhi), y = as.numeric(GOI), fill = cluster_neuhi)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = 0.3, alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + scale_fill_manual(values = c(orange,skyblue,bluishgreen,yellow,blue,vermillion,"purple")) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

gene <- "FCGR3A"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_filtered$cluster_neuhi <- mapvalues(metadata_filtered$cluster_neuhi, from = c("1","2","3","4","5","6","7"), to = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_filtered$cluster_neuhi <- factor(metadata_filtered$cluster_neuhi, levels = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
kruskal.test(g = metadata_temp$cluster_neuhi, x = metadata_temp$GOI)$p.value
p5 <- ggplot(metadata_temp, aes(x = factor(cluster_neuhi), y = as.numeric(GOI), fill = cluster_neuhi)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = 0.3, alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + scale_fill_manual(values = c(orange,skyblue,bluishgreen,yellow,blue,vermillion,"purple")) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

gene <- "FCGR3B"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_filtered$cluster_neuhi <- mapvalues(metadata_filtered$cluster_neuhi, from = c("1","2","3","4","5","6","7"), to = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_filtered$cluster_neuhi <- factor(metadata_filtered$cluster_neuhi, levels = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
kruskal.test(g = metadata_temp$cluster_neuhi, x = metadata_temp$GOI)$p.value
p6 <- ggplot(metadata_temp, aes(x = factor(cluster_neuhi), y = as.numeric(GOI), fill = cluster_neuhi)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = 0.3, alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + scale_fill_manual(values = c(orange,skyblue,bluishgreen,yellow,blue,vermillion,"purple")) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

gene <- "FCAR"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_filtered$cluster_neuhi <- mapvalues(metadata_filtered$cluster_neuhi, from = c("1","2","3","4","5","6","7"), to = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_filtered$cluster_neuhi <- factor(metadata_filtered$cluster_neuhi, levels = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
kruskal.test(g = metadata_temp$cluster_neuhi, x = metadata_temp$GOI)$p.value
p7 <- ggplot(metadata_temp, aes(x = factor(cluster_neuhi), y = as.numeric(GOI), fill = cluster_neuhi)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = 0.3, alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + scale_fill_manual(values = c(orange,skyblue,bluishgreen,yellow,blue,vermillion,"purple")) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

gene <- "FCGRT"
id <- genepc$Gene.stable.ID[which(genepc$Gene.name == gene)][1]
metadata_filtered$GOI <- t(logTPM_filtered[rownames(logTPM_filtered) == id,])
metadata_filtered$cluster_neuhi <- mapvalues(metadata_filtered$cluster_neuhi, from = c("1","2","3","4","5","6","7"), to = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_filtered$cluster_neuhi <- factor(metadata_filtered$cluster_neuhi, levels = c("NMF1","NMF2","NMF3","NMF4","NMF5","NMF6","Neu-Lo"))
metadata_temp <- metadata_filtered[metadata_filtered$COVID == "Positive" & metadata_filtered$Day %in% c("D0","D3","D7"),]
kruskal.test(g = metadata_temp$cluster_neuhi, x = metadata_temp$GOI)$p.value
p8 <- ggplot(metadata_temp, aes(x = factor(cluster_neuhi), y = as.numeric(GOI), fill = cluster_neuhi)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = 0.3, alpha = 0.2, size = 0.5) + theme_bw() + ylab("log2(TPM+1) Expression") + scale_fill_manual(values = c(orange,skyblue,bluishgreen,yellow,blue,vermillion,"purple")) + stat_compare_means() + ggtitle(gene) + theme(legend.position = "none") + xlab("")

cowplot::plot_grid(p1,p2,p3,p4,p5,p6,p7,p8,ncol=4)
```















